sudo: false
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - 'node'
  - '6'
  - '5'
  - '4'
  - '0.12'
script:
  - npm run validate
after_success:
  - npm run semantic-release
branches:
  only:
    - master
